name:                jmespath
version:             0.1.0.0
github:              "quasarbright/jmespath"
license:             BSD3
author:              "mdelmonaco"
maintainer:          "mdelmonacochs@gmail.com"
copyright:           "Mike Delmonaco 2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quasarbright/jmespath#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- mtl
- extra
- transformers
- lens
- aeson
- text
- vector
- unordered-containers

ghc-options:
- -w
- -Wall

library:
  source-dirs: src
  default-extensions:
  - LambdaCase
  - RecordWildCards
  - GeneralizedNewtypeDeriving
  - TupleSections
  - MonadComprehensions
  - MultiWayIf


executables:
  jmespath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -w
    - -Wall
    dependencies:
    - jmespath
    default-extensions:
    - LambdaCase
    - RecordWildCards
    - GeneralizedNewtypeDeriving
    - TupleSections
    - MonadComprehensions
    - MultiWayIf

tests:
  jmespath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -w
    - -Wall
    dependencies:
    - jmespath
    - hspec
    - QuickCheck
    - HUnit
    default-extensions:
    - LambdaCase
    - RecordWildCards
    - GeneralizedNewtypeDeriving
    - TupleSections
    - MonadComprehensions
    - MultiWayIf
